import { formatSize } from '../utils.js';

export const name = 'diskwala';

export const hosts = new Set([
  'diskwala.com',
  'www.diskwala.com',
  'diskwala.net',
  'www.diskwala.net',
  'diskwala.app',
  'www.diskwala.app',
]);

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36';

const BROWSER_HEADERS = {
  'User-Agent': UA,
  Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
  'Accept-Language': 'en-US,en;q=0.9',
  Referer: 'https://diskwala.net/',
  DNT: '1',
};

export function downloadHeaders() {
  return {
    'User-Agent': UA,
    Accept: '*/*',
    'Accept-Language': 'en-US,en;q=0.9',
    Referer: 'https://diskwala.net/',
    DNT: '1',
  };
}

// Direct media URLs embedded in the page (plain or JSON-escaped).
const MEDIA_RE = /https?:\/\/[^\s"'<>\\]+?\.(?:mp4|mkv|webm|mov|m4v|mp3|zip|apk)(?:\?[^\s"'<>\\]*)?/gi;
// JSON properties commonly used by these pages, e.g. "downloadUrl": "https://...".
const PROP_RE =
  /"(?:downloadUrl|download_url|downloadLink|fileUrl|file_url|videoUrl|video_url|streamUrl|stream_url|src|url)"\s*:\s*"(https?:\/\/[^"]+)"/gi;

function clean(u) {
  return u.replace(/\\\//g, '/').replace(/&amp;/g, '&');
}

// NOTE (verified 2026-09): Diskwala's API (ddudapidd.diskwala.com) requires a
// per-request Appicrypt signature generated by a browser-only WASM module
// (spawns Web Workers), their share pages no longer offer anonymous playback
// ("Open in the app" wall), and /file/sign requires a logged-in session.
// Server-side resolution is therefore not possible without a logged-in
// Diskwala account browser session. This provider keeps a best-effort page
// scan in case that ever changes, then explains the situation.
export async function resolveInfo(shareUrl, ctx) {
  const timeout = AbortSignal.timeout(ctx.timeoutMs);
  const resp = await fetch(shareUrl, {
    headers: BROWSER_HEADERS,
    redirect: 'follow',
    signal: timeout,
  });
  if (!resp.ok) throw new Error(`Diskwala page fetch failed (HTTP ${resp.status})`);
  const html = await resp.text();

  const found = new Map();
  for (const m of html.matchAll(PROP_RE)) {
    const u = clean(m[1]);
    if (/\.(jpe?g|png|webp|gif|css|js)(\?|$)/i.test(u)) continue;
    found.set(u, u);
  }
  for (const m of html.matchAll(MEDIA_RE)) {
    found.set(clean(m[0]), clean(m[0]));
  }

  const urls = [...found.values()];
  if (!urls.length) {
    throw new Error(
      'Diskwala now requires their mobile app and a signed login session to fetch files, so server-side downloads are blocked for everyone right now. Terabox links work fully — send one of those instead!',
    );
  }

  const files = urls.map((u, i) => {
    let base = '';
    try {
      base = decodeURIComponent(new URL(u).pathname.split('/').pop() || '');
    } catch {
      base = '';
    }
    return {
      name: base || `file_${i + 1}`,
      size: formatSize(0),
      size_bytes: 0,
      thumbnail: '',
      dlink: u,
      is_dir: false,
      path: '',
      fs_id: '',
    };
  });

  return {
    provider: name,
    share_url: shareUrl,
    final_url: resp.url,
    surl: '',
    title: '',
    files,
  };
}
